---
PORT: 3003
MONGODB:
  URL: 'mongodb://127.0.0.1:27017/okr'
  DB: okr
  USE_SSL: false
  KEY_PATH:
  CERT_PATH:
  CA_PATH:
TWS:
  APP_ID: 5ad40e4b97706200af73695c
  AUTH:
    URL: http://192.168.0.25:31090
    SECRET: AOCxAoEHRwBuUVobuBFuegnhsApeettN
    CACHE_PREFIX: OKR_AUTH
    RESOURCE_TYPE: self
  ORG:
    URL: http://192.168.0.25:31103
CORE:
  HOST: http://project.ci/api
RATELIMIT:
  PREFIX: ork:LIMIT
  POLICY:
    GET: [300, 60000]
    POST: [300, 60000]
REDIS: 192.168.0.21:6379
CLIENT_ID: 7c50b220-a747-11e8-8f87-09548cf94568
CLIENT_SECRET: 03f59edb-1b24-4d35-9628-cf79f2beb792
AUTH_URL: http://project.ci/oauth2/access_token
SESSION:
  DOMAIN: .project.ci
  NAME: TEAMBITION_SESSIONID
  KEYS:
  - tb-accounts
GRADINGSTANDARD:
  [
    {
      score: 30,
      describe: '我们知道肯定能达成的程度。只需要很少的帮助或不需要帮助就能达成的程度。'
    },
    {
      score: 70,
      describe: '这是我们希望能达成的程度。虽然很难但是可以达成。'
    },
    {
      score: 100,
      describe: '结果远超预期：几乎不可达成。'
    }
  ]